name: KittyCanon
version: '${project.version}'
main: me.kavin.kittycanon.KittyCanon
api-version: '1.20'
softdepend: [ ProtocolLib ]
commands:
  cat:
    description: "This will spawn an exploding car"
    usage: "/cat [black]"
    aliases: [car]
    permission: kittycanon.command.cat
    permission-message: "You are not car enough"
  kit:
    description: "This will give you a kit"
    usage: "/kit [gang]"
    aliases: [ Super ]
    permission: kittycanon.command.kit
    permission-message: "You are not kit enough"